name: Microservice

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # -------------------------
    # Setup .NET
    # -------------------------
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clean UsersService Backend
      run: dotnet clean Ecommerce.UsersService/Ecommerce.UsersService.slnx

    - name: Restore UsersService Backend
      run: dotnet restore Ecommerce.UsersService/Ecommerce.UsersService.slnx

    - name: Build UsersService Backend
      run: dotnet build --no-restore Ecommerce.UsersService/Ecommerce.UsersService.slnx

    - name: Clean ProductService Backend
      run: dotnet clean Ecommerce.ProductService/Ecommerce.ProductService.slnx

    - name: Restore ProductService Backend
      run: dotnet restore Ecommerce.ProductService/Ecommerce.ProductService.slnx

    - name: Build ProductService Backend
      run: dotnet build --no-restore Ecommerce.ProductService/Ecommerce.ProductService.slnx

    # -------------------------
    # Setup Node (Angular)
    # -------------------------
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Angular Dependencies
      working-directory: UserServiceAngularApp
      run: npm ci

    - name: Build Angular App
      working-directory: UserServiceAngularApp
      run: npm run build -- --configuration production
